### ISSUE TITLE
Version 1.0 Release Roadmap

### ISSUE THREAD

**Issue by jakevdp** [ellisonbg/altair#120]
We're getting close to release I think. Here's what I have in mind:

- [x] Merge new schema interface (#116)
- [x] Merge new configure interface (#123)
- [x] update code generation to use new configure interface (#127)
- [x] Rename ``Layer`` to ``Chart`` (#125)
- [x] Update Vega-Lite schema to 1.0.10+ and update wrappers (#128)
- [x] Address bugs #90 & #91
- [x] Maybe add auto-generation of ``Encoding``/``Facet``?
- [x] Maybe add auto-generation of ``Chart`` and other higher-level wrappers? (decorator solution instead: see #129 & https://github.com/ellisonbg/altair/commit/bc9b1c66945aeaefe0da8cc42298dcfff01cf1be)
- [x] Implement other top-level objects exposed in vega-lite 1.0.10+?
- [x] Add `+` syntax for creating ``LayeredChart`` (#137)
- [x] Add regression notebook (#138)
- [x] Do another ``ipyvega`` release with vega-lite 1.0.12
- [x] One more pass through docs and examples; in particular add examples of ``FacetedChart`` and ``LayeredChart`` (#137)
- [x] Create conda-forge recipe (#89)

**Comment by ellisonbg** [comment]
I think this is a pretty good map. How do we want to version this release?

**Comment by jakevdp** [comment]
I'm thinking we do 1.0: it's mirroring the 1.0 Vega-lite spec, and I feel like we've hit on a pretty good API that will be able to absorb any future enhancements to Vega-lite.

**Comment by ellisonbg** [comment]
OK I think that sounds good - I was wondering if we want to have our major
versions follow that of vega-lite and ipyvega

On Wed, Jun 8, 2016 at 8:21 AM, Jake Vanderplas <notifications@github.com>
wrote:

> I'm thinking we do 1.0: it's mirroring the 1.0 Vega-lite spec, and I feel
> like we've hit on a pretty good API that will be able to absorb any future
> enhancements to Vega-lite.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/issues/120#issuecomment-224623924>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0BjWVn2CKdpin1Kpf8EPUO6a9IEIks5qJt3sgaJpZM4It03Y>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
> major versions follow that of vega-lite and ipyvega

Since altair & vega-lite are so closely related, I think that would be a great approach here. For ipyvega it's less clear to me, because the package depends on other codebases too (vega, polestar, etc.)

**Comment by jakevdp** [comment]
We're getting close. One thing to decide: the 1.0.10 schema update added two new top-level objects, which I chose to call ``LayeredChart`` and ``FacetedChart``. I thought about simply ``Layer`` and ``Facet``, but ``Facet`` is already taken as a lower-level definition.

I'm not entirely married to those names – do you have any thoughts on them?

**Comment by kanitw** [comment]
+1  to `LayeredChart` and `FacetedChart`.

**Comment by ellisonbg** [comment]
I like these names.  Also:

* Would like to support `+` for creating `LayeredChart` objects.
* Would like to have an API that allows a user to pre-create a 2d array of
charts and then access them using python's array indexing, such as
`charts[i,j].encode(...)` or something pythonic.




On Sun, Jun 12, 2016 at 9:31 PM, Kanit Wongsuphasawat <
notifications@github.com> wrote:

> +1 to LayeredChart and FacetedChart.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/issues/120#issuecomment-225487310>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0LRbS8IM-RHQmC1snFo_J_Mi1A7yks5qLN0sgaJpZM4It03Y>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
Do you imagine the array-based creation acting somewhat like ``plt.subplots``?

**Comment by ellisonbg** [comment]
Yes, that was one api I thought about, but it isn't clear if that is the
right model. But it is one that folks would be familiar with. Also, it
would be nicer than having to pass nested lists or something.

On Thu, Jun 16, 2016 at 7:04 PM, Jake Vanderplas <notifications@github.com>
wrote:

> Do you imagine the array-based creation acting somewhat like plt.subplots?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/issues/120#issuecomment-226662750>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0N3rQqJPhHNzZhykr_SMRkbfd4RGks5qMgCcgaJpZM4It03Y>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
I'm not certain there's a Vega-Lite analog to subplots currently – I think that currently Facets must be constructed via encoding rows and columns.

**Comment by ellisonbg** [comment]
Ahh, OK I will have to look at the spec and see what exactly is exposed.

On Thu, Jun 16, 2016 at 7:23 PM, Jake Vanderplas <notifications@github.com>
wrote:

> I'm not certain there's a Vega-Lite analog to subplots currently – I think
> that currently Facets must be constructed via encoding rows and columns.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/issues/120#issuecomment-226664896>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0HVL5uwgmJVWUA479VOtTDBRVhvaks5qMgUXgaJpZM4It03Y>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Released!!!

**Comment by kanitw** [comment]
Wow!
